### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by mcampbellcisco** [snyk/event-loop-spinner#5]
What license is this released under?

**Comment by FauxFaux** [comment]
There's a license stated in the `package.json`: https://github.com/snyk/event-loop-spinner/blob/585fa507971ae1f66798c3947fd479558ffe9abf/package.json#L36

If we were to carefully think this through, it would probably end up as Apache2 like our other open source projects. Do you care?

**Comment by mcampbellcisco** [comment]
Thanks @FauxFaux ; I missed that.  Any of Apache2, MIT, or BSD is fine with me.  My particular use case is submission of all the FOSS libs we use for compliance, and the tool gripes if it can't find a `LICENSE` file to parse.  I can circumvent the scanning with a manual entry, which I did, so nothing required for this right now.  Up to you if you want to close this as-is or not.
