### ISSUE TITLE
suggestion: spinIfStarving

### ISSUE THREAD

**Issue by LiranBri** [snyk/event-loop-spinner#8]
I suggest to add an extra unified *spinIfStarving* method, which would be equivalent to just doing
```
    if (eventLoopSpinner.isStarving()) {
      await eventLoopSpinner.spin();
    }
```

I think the common use-case would be to use those in combination, so why not minimize the three lines of code into one?
if agreed, I'll make a PR

**Comment by FauxFaux** [comment]
This is amazingly slow, see https://github.com/snyk/event-loop-spinner/issues/7#issuecomment-952056775
